import os
# os.makedirs('G:\python by durga\sai\sai1\sai2')
# print('Dirctoy created succesfully')
# os.rmdir('G:\python by durga\sai\sai1')
# print('Dirctoy removed succesfully')
# os.rename('G:\python del','G:\python delete')
# print('Dirctory  names are  succesfully changed')
# list=os.listdir('G:\python by durga')
# for name in list:
#     print(name)
# print('no of Dirs:',len(list))
#os.system('python writing.py')
# for dirpath,dirnames,filenames in os.walk('G:\python by durga'):
#     print('dir path:',dirpath)
#     print('dir names:', dirnames)
#     print('files:', filenames)
#     print()
#     print()
#os.system('Notepad')
print(os.stat('input.py'))